### ISSUE TITLE
Вопрос по архитектуре

### ISSUE THREAD

**Issue by Desire456** [Desire456/spring-course-3#8]
Столкнулся с такой проблемой: в сервисах возвращаю, например, в методе findById  дто объект. Потом я хочу в другом месте его использовать, но уже хочу ентити получить, а не дто. В связи с этим вопрос как лучше поступить при написании сервиса, чтобы таких проблем не возникало: возвращать ентити везде, а в прикладных местах мапить в дто или писать в сервисах кучу методов с разными return типами? @coursar, подскажите, пожалуйста?

**Comment by coursar** [comment]
В таких случаях лучше юзать напрямую репозитории.

**Comment by Desire456** [comment]
в таком случае нужно будет каждый раз писать orElseThrow() - не очень хочется так делать

**Comment by coursar** [comment]
Варианты:
1. Вы можете в репо сделать дефолтный метод `findByIdOrThrow`, который дёргает оригинальный метод и делает `throw` за вас
2. Ввести прослойку `ServiceForRepo`, который всегда возвращает `Entity`. Тогда в `Service`, которые бизнесовые, вы будете юзать их
2. Делать два метода - один возвращает Dto, второй - Entity

**Comment by Desire456** [comment]
Понял, спасибо!
